name: chacha-environment
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - geopandas
  - rasterio
  - xarray
  - seaborn
  - pip:
    - geodatasets
    - SALib
    - py_hydroweb
    - pystac_client